---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/mundos-perdidos/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp CNAME $DEPLOYPATH
